# Compose fileのバージョン指定
version: '3'

# どんなコンテナを立ち上げるか
services:

  # ---------------------------------
  # PHP5.6 + Apache
  # ---------------------------------
  myapp-web:
    container_name: myapp-web
    ports:
      - "80:80"
    # ./docker/app/Dockerfile でイメージをビルド
    build: ./docker/app
    # ローカルの ./src ディレクトリを
    # コンテナの /var/www/html にマウント
    volumes:
      - ./src:/var/www/html

  # ----------------------------------
  # MailCatcherを動かすコンテナ
  # ----------------------------------
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  # ----------------------------------
  # Postgresを動かすコンテナ
  # ----------------------------------
  myapp-db:
    container_name: myapp-db
    image: postgres:9.3
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: sample-user
      POSTGRES_PASSWORD: samplepassword
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      # SAMPLE用 DBテーブル
      - ./docker/initdb:/docker-entrypoint-initdb.d
      # PostgreSQLの永続化（利用する場合は上のSAMPLEをコメントアウトする）
      #- /tmp/postgresql-data:/var/lib/postgresql/data:z

  # ----------------------------------
  # pgAdminを動かすコンテナ
  # ----------------------------------
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 81:80
    # pgAdminのログイン情報
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@laraweb.net
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - myapp-db

volumes:
  pgadmin:
